export const ALL_COLUMNS = [
    { id: 'created_dt', label: 'Created Date' },
    { id: 'data_source_modified_dt', label: 'Modified Date' },
    { id: 'entity_type', label: 'Entity' },
    { id: 'operating_status', label: 'Operating Status' },
    { id: 'legal_name', label: 'Legal Name' },
    { id: 'dba_name', label: 'DBA Name' },
    { id: 'physical_address', label: 'Physical Address' },
    { id: 'p_street', label: 'Street' },
    { id: 'p_city', label: 'City' },
    { id: 'p_state', label: 'State' },
    { id: 'p_zip_code', label: 'Zip Code' },
    { id: 'phone', label: 'Phone' },
    { id: 'mailing_address', label: 'Mailing Address' },
    { id: 'm_street', label: 'Mailing Street' },
    { id: 'm_city', label: 'Mailing City' },
    { id: 'm_state', label: 'Mailing State' },
    { id: 'm_zip_code', label: 'Mailing Zip Code' },
    { id: 'usdot_number', label: 'DOT' },
    { id: 'mc_mx_ff_number', label: 'MC/MX/FF' },
    { id: 'power_units', label: 'Power Units' },
    { id: 'mcs_150_form_date', label: 'MCS-150 Form Date' },
    { id: 'out_of_service_date', label: 'Out of Service Date' },
    { id: 'state_carrier_id_number', label: 'State Carrier ID' },
    { id: 'duns_number', label: 'DUNS Number' },
    { id: 'drivers', label: 'Drivers' },
    { id: 'mcs_150_mileage_year', label: 'MCS-150 Mileage Year' },
    { id: 'id', label: 'ID' },
    { id: 'credit_score', label: 'Credit Score' },
    { id: 'record_status', label: 'Record Status' },
];